version: "3.7"

services:
  diageo-1:
    image: local/nats:alpine
    container_name: diageo-1
    command: --name diageo-1 -c /config/diageo/edge-leaf.conf
    restart: always
    volumes:
      - ./config:/config
    networks:
      - diageo
      - saas
  diageo-2:
    image: local/nats:alpine
    container_name: diageo-2
    command: --name diageo-2 -c /config/diageo/edge.conf
    restart: always
    volumes:
      - ./config:/config
    networks:
      - diageo
  diageo-3:
    image: local/nats:alpine
    container_name: diageo-3
    command: --name diageo-3 -c /config/diageo/edge.conf
    restart: always
    volumes:
      - ./config:/config
    networks:
      - diageo

# this creates a new network named diageo_net
networks:
  diageo: 