version: "3.7"

services:
  hsbc-1:
    image: local/nats:alpine
    container_name: hsbc-1
    command: --name hsbc-1 -c /config/hsbc-1/edge-leaf.conf
    restart: always
    volumes:
      - ./config:/config
    networks:
      - hsbc
      - saas
  hsbc-2:
    image: local/nats:alpine
    container_name: hsbc-2
    command: --name hsbc-2 -c /config/hsbc-1/edge.conf
    restart: always
    volumes:
      - ./config:/config
    networks:
      - hsbc
  hsbc-3:
    image: local/nats:alpine
    container_name: hsbc-3
    command: --name hsbc-2 -c /config/hsbc-1/edge.conf
    restart: always
    volumes:
      - ./config:/config
    networks:
      - hsbc
  hsbc-4:
    image: local/nats:alpine
    container_name: hsbc-4
    command: --name hsbc-4 -c /config/hsbc-2/edge-leaf.conf
    restart: always
    volumes:
      - ./config:/config
    networks:
      - hsbc
      - saas
  hsbc-5:
    image: local/nats:alpine
    container_name: hsbc-5
    command: --name hsbc-5 -c /config/hsbc-2/edge.conf
    restart: always
    volumes:
      - ./config:/config
    networks:
      - hsbc
  hsbc-6:
    image: local/nats:alpine
    container_name: hsbc-6
    command: --name hsbc-6 -c /config/hsbc-2/edge.conf
    restart: always
    volumes:
      - ./config:/config
    networks:
      - hsbc

# this creates a new network named hsbc_net
networks:
  hsbc: 